# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: lint_build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        folder: [website, server]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.20.2
      uses: actions/setup-node@v3
      with:
        node-version: 18.20.2
        cache: 'yarn'
        cache-dependency-path: ./${{ matrix.folder }}/yarn.lock

    - name: "${{ matrix.folder }}: install"
      run: yarn install --immutable --immutable-cache --check-cache
      working-directory: ./${{ matrix.folder }}
    - name: "${{ matrix.folder }}: lint"
      run: yarn lint
      working-directory: ./${{ matrix.folder }}
    - name: "${{ matrix.folder }}: build"
      run: yarn build
      working-directory: ./${{ matrix.folder }}
